export const BUSINESS = {
  name: "SynovaTech",
  fullName: "SynovaTech PTY",
  tagline: "Soluciones Tecnologicas Integrales",
  slogan: "Entrega Inmediata",
  instagram: "@synovatechpty",
  instagramUrl: "https://www.instagram.com/synovatechpty/",
  linktree: "https://linktr.ee/synovatechpty",
  email: "innovastyle@in-novasolution.com",
  whatsapp: "50760434542",
  whatsappDisplay: "6043-4542",
  services: [
    "Software 100% original: Windows | Office",
    "Configuracion de correos con dominio en GoDaddy",
    "Instalacion remota rapida y segura",
    "Mesas Gamer con envio gratis a todo Panama",
  ],
  payment: {
    yappy: [
      { name: "Jorge Choy", number: "6043-4542" },
      { name: "Daysi Torres", number: "6537-0196" },
    ],
    ach: {
      bank: "Banco General",
      type: "Cuenta de Ahorros",
      holder: "Jorge Choy",
      account: "0472984345786",
    },
  },
};

export interface Product {
  id: string;
  name: string;
  category: "software" | "mesa";
  subcategory: string;
  price: number;
  description: string;
  features: string[];
  type?: string; // OEM / Retail
  stock?: number;
  dimensions?: string;
  delivery: string;
  image?: string;
}

export const SOFTWARE_PRODUCTS: Product[] = [
  // Windows 11
  {
    id: "win11-home-oem",
    name: "Windows 11 Home OEM",
    category: "software",
    subcategory: "Windows 11",
    price: 10,
    type: "OEM",
    description: "Licencia original de Windows 11 Home. Ideal para uso personal y del hogar.",
    features: ["Licencia original Microsoft", "Activacion permanente", "1 PC", "Entrega inmediata por email", "Soporte de instalacion remota"],
    delivery: "Inmediata - Recibe tu clave por email y WhatsApp",
  },
  {
    id: "win11-home-retail",
    name: "Windows 11 Home Retail",
    category: "software",
    subcategory: "Windows 11",
    price: 15,
    type: "Retail",
    description: "Licencia original Windows 11 Home transferible. Puedes moverla a otro PC.",
    features: ["Licencia original Microsoft", "Activacion permanente", "Transferible a otro PC", "Entrega inmediata por email", "Soporte de instalacion remota"],
    delivery: "Inmediata - Recibe tu clave por email y WhatsApp",
  },
  {
    id: "win11-pro-oem",
    name: "Windows 11 Pro OEM",
    category: "software",
    subcategory: "Windows 11",
    price: 12,
    type: "OEM",
    description: "Licencia original Windows 11 Pro. Incluye BitLocker, escritorio remoto y mas.",
    features: ["Licencia original Microsoft", "Activacion permanente", "BitLocker, Hyper-V, Remote Desktop", "1 PC", "Entrega inmediata por email", "Soporte de instalacion remota"],
    delivery: "Inmediata - Recibe tu clave por email y WhatsApp",
  },
  {
    id: "win11-pro-retail",
    name: "Windows 11 Pro Retail",
    category: "software",
    subcategory: "Windows 11",
    price: 17,
    type: "Retail",
    description: "Licencia original Windows 11 Pro transferible. La version mas completa.",
    features: ["Licencia original Microsoft", "Activacion permanente", "Transferible a otro PC", "BitLocker, Hyper-V, Remote Desktop", "Entrega inmediata por email", "Soporte de instalacion remota"],
    delivery: "Inmediata - Recibe tu clave por email y WhatsApp",
  },
  // Windows 10
  {
    id: "win10-home-oem",
    name: "Windows 10 Home OEM",
    category: "software",
    subcategory: "Windows 10",
    price: 8,
    type: "OEM",
    description: "Licencia original Windows 10 Home. Compatible con la mayoria de PCs.",
    features: ["Licencia original Microsoft", "Activacion permanente", "1 PC", "Entrega inmediata por email", "Soporte de instalacion remota"],
    delivery: "Inmediata - Recibe tu clave por email y WhatsApp",
  },
  {
    id: "win10-pro-oem",
    name: "Windows 10 Pro OEM",
    category: "software",
    subcategory: "Windows 10",
    price: 10,
    type: "OEM",
    description: "Licencia original Windows 10 Pro. Ideal para profesionales y empresas.",
    features: ["Licencia original Microsoft", "Activacion permanente", "BitLocker, Remote Desktop", "1 PC", "Entrega inmediata por email", "Soporte de instalacion remota"],
    delivery: "Inmediata - Recibe tu clave por email y WhatsApp",
  },
  // Office
  {
    id: "office-2016",
    name: "Office Profesional Pro Plus 2016",
    category: "software",
    subcategory: "Microsoft Office",
    price: 10,
    description: "Suite completa de Office 2016: Word, Excel, PowerPoint, Outlook y mas.",
    features: ["Word, Excel, PowerPoint, Outlook, Access, Publisher", "Licencia original Microsoft", "Activacion permanente", "1 PC", "Entrega inmediata por email", "Soporte de instalacion remota"],
    delivery: "Inmediata - Recibe tu clave por email y WhatsApp",
  },
  {
    id: "office-2019",
    name: "Office Profesional Pro Plus 2019",
    category: "software",
    subcategory: "Microsoft Office",
    price: 15,
    description: "Suite completa de Office 2019 con funciones mejoradas y mejor rendimiento.",
    features: ["Word, Excel, PowerPoint, Outlook, Access, Publisher", "Licencia original Microsoft", "Activacion permanente", "1 PC", "Entrega inmediata por email", "Soporte de instalacion remota"],
    delivery: "Inmediata - Recibe tu clave por email y WhatsApp",
  },
  {
    id: "office-2021",
    name: "Office Profesional Pro Plus 2021",
    category: "software",
    subcategory: "Microsoft Office",
    price: 25,
    description: "Suite completa de Office 2021. Incluye las ultimas funciones sin suscripcion.",
    features: ["Word, Excel, PowerPoint, Outlook, Access, Publisher, Teams", "Licencia original Microsoft", "Activacion permanente", "1 PC", "Entrega inmediata por email", "Soporte de instalacion remota"],
    delivery: "Inmediata - Recibe tu clave por email y WhatsApp",
  },
  {
    id: "office-2024",
    name: "Office Profesional Pro Plus 2024",
    category: "software",
    subcategory: "Microsoft Office",
    price: 45,
    description: "La version mas reciente de Office. Maxima compatibilidad y funciones con IA.",
    features: ["Word, Excel, PowerPoint, Outlook, Access, Publisher, Teams", "Licencia original Microsoft", "Activacion permanente", "Funciones de IA incluidas", "1 PC", "Entrega inmediata por email", "Soporte de instalacion remota"],
    delivery: "Inmediata - Recibe tu clave por email y WhatsApp",
  },
  // Windows Server
  {
    id: "ws-2012-std",
    name: "Windows Server 2012 Standard Retail",
    category: "software",
    subcategory: "Windows Server",
    price: 12,
    description: "Windows Server 2012 Standard. Ideal para servidores con cargas de trabajo basicas.",
    features: ["Licencia original Microsoft", "Activacion permanente", "Entrega inmediata por email", "Soporte de instalacion remota"],
    delivery: "Inmediata - Recibe tu clave por email y WhatsApp",
  },
  {
    id: "ws-2019-std",
    name: "Windows Server 2019 Standard Retail",
    category: "software",
    subcategory: "Windows Server",
    price: 15,
    description: "Windows Server 2019 Standard. Excelente estabilidad para entornos empresariales.",
    features: ["Licencia original Microsoft", "Activacion permanente", "Hyper-V, Storage Spaces", "Entrega inmediata por email", "Soporte de instalacion remota"],
    delivery: "Inmediata - Recibe tu clave por email y WhatsApp",
  },
  {
    id: "ws-2019-dc",
    name: "Windows Server 2019 Datacenter Retail",
    category: "software",
    subcategory: "Windows Server",
    price: 25,
    description: "Windows Server 2019 Datacenter. Sin limites de virtualizacion.",
    features: ["Licencia original Microsoft", "Activacion permanente", "Virtualizacion ilimitada", "Shielded VMs", "Entrega inmediata por email", "Soporte de instalacion remota"],
    delivery: "Inmediata - Recibe tu clave por email y WhatsApp",
  },
  {
    id: "ws-2022-dc",
    name: "Windows Server 2022 Datacenter Retail",
    category: "software",
    subcategory: "Windows Server",
    price: 30,
    description: "Windows Server 2022 Datacenter. Seguridad avanzada y soporte Azure hibrido.",
    features: ["Licencia original Microsoft", "Activacion permanente", "Virtualizacion ilimitada", "Seguridad avanzada", "Azure hybrid", "Entrega inmediata por email", "Soporte de instalacion remota"],
    delivery: "Inmediata - Recibe tu clave por email y WhatsApp",
  },
  {
    id: "ws-2025-std",
    name: "Windows Server 2025 Standard Retail",
    category: "software",
    subcategory: "Windows Server",
    price: 25,
    description: "Windows Server 2025 Standard. La version mas reciente para servidores.",
    features: ["Licencia original Microsoft", "Activacion permanente", "Soporte extendido", "Entrega inmediata por email", "Soporte de instalacion remota"],
    delivery: "Inmediata - Recibe tu clave por email y WhatsApp",
  },
  {
    id: "ws-2025-dc",
    name: "Windows Server 2025 Datacenter Retail",
    category: "software",
    subcategory: "Windows Server",
    price: 35,
    description: "Windows Server 2025 Datacenter. Lo mas nuevo en servidores empresariales.",
    features: ["Licencia original Microsoft", "Activacion permanente", "Virtualizacion ilimitada", "Todas las funciones enterprise", "Entrega inmediata por email", "Soporte de instalacion remota"],
    delivery: "Inmediata - Recibe tu clave por email y WhatsApp",
  },
];

export const DESK_PRODUCTS: Product[] = [
  {
    id: "mesa-h2-led",
    name: "Mesa Gamer H2",
    category: "mesa",
    subcategory: "Mesas Gamer",
    price: 110,
    stock: 13,
    dimensions: "140 x 60 x 73 cm",
    description: "Mesa gamer con luces LED integradas. Diseno moderno y resistente para tu setup gaming.",
    features: ["Luces LED integradas", "Estructura de acero resistente", "Superficie antideslizante", "Porta vasos y gancho para audifonos", "140 x 60 x 73 cm", "Envio GRATIS a todo Panama"],
    delivery: "Envio gratis a todo Panama por Red Servi (3-5 dias habiles)",
  },
  {
    id: "mesa-electrica-negra",
    name: "Mesa Electrica Ajustable - Negra",
    category: "mesa",
    subcategory: "Mesas Electricas",
    price: 130,
    stock: 8,
    dimensions: "140 x 60 x 81-118 cm (ajustable)",
    description: "Mesa con motor electrico de altura ajustable. Trabaja sentado o de pie con un boton.",
    features: ["Motor electrico de ajuste de altura", "Rango: 81 a 118 cm", "Color: Negro", "Panel de control integrado", "140 x 60 cm superficie", "Envio GRATIS a todo Panama"],
    delivery: "Envio gratis a todo Panama por Red Servi (3-5 dias habiles)",
  },
  {
    id: "mesa-electrica-blanca",
    name: "Mesa Electrica Ajustable - Blanca",
    category: "mesa",
    subcategory: "Mesas Electricas",
    price: 130,
    stock: 10,
    dimensions: "140 x 60 x 81-118 cm (ajustable)",
    description: "Mesa con motor electrico de altura ajustable en color blanco. Elegante y funcional.",
    features: ["Motor electrico de ajuste de altura", "Rango: 81 a 118 cm", "Color: Blanco", "Panel de control integrado", "140 x 60 cm superficie", "Envio GRATIS a todo Panama"],
    delivery: "Envio gratis a todo Panama por Red Servi (3-5 dias habiles)",
  },
  {
    id: "mesa-r5-7",
    name: "Mesa Gamer R5-7",
    category: "mesa",
    subcategory: "Mesas Gamer",
    price: 95,
    stock: 36,
    dimensions: "140 x 60 x 73 cm",
    description: "Mesa gamer resistente y espaciosa. Excelente relacion calidad-precio.",
    features: ["Estructura de acero reforzado", "Superficie amplia", "Diseno ergonomico", "Porta vasos y gancho para audifonos", "140 x 60 x 73 cm", "Envio GRATIS a todo Panama"],
    delivery: "Envio gratis a todo Panama por Red Servi (3-5 dias habiles)",
  },
  {
    id: "mesa-z5-6",
    name: "Mesa Gamer Z5-6",
    category: "mesa",
    subcategory: "Mesas Gamer",
    price: 95,
    stock: 22,
    dimensions: "140 x 60 x 73 cm",
    description: "Mesa gamer con diseno Z estilizado. Estable y con espacio para todo tu equipo.",
    features: ["Diseno en Z estilizado", "Estructura de acero", "Superficie amplia antideslizante", "Porta vasos y gancho para audifonos", "140 x 60 x 73 cm", "Envio GRATIS a todo Panama"],
    delivery: "Envio gratis a todo Panama por Red Servi (3-5 dias habiles)",
  },
  {
    id: "mesa-s60-led",
    name: "Mesa Electrica S60 con Motor + LED",
    category: "mesa",
    subcategory: "Mesas Electricas",
    price: 145,
    stock: 12,
    dimensions: "140 x 60 x 81-118 cm (ajustable)",
    description: "La mesa mas completa: motor electrico ajustable + luces LED. Lo mejor de ambos mundos.",
    features: ["Motor electrico de ajuste de altura", "Luces LED integradas", "Rango: 81 a 118 cm", "Panel de control", "140 x 60 cm superficie", "Envio GRATIS a todo Panama"],
    delivery: "Envio gratis a todo Panama por Red Servi (3-5 dias habiles)",
  },
  {
    id: "mesa-s2-l",
    name: 'Mesa Gamer S2 Reversible (Forma "L" o Recta)',
    category: "mesa",
    subcategory: "Mesas Gamer",
    price: 125,
    stock: 10,
    dimensions: "190 x 60 x 73 cm",
    description: 'Mesa gamer reversible que puedes usar en forma de "L" o recta. La mas grande y versatil.',
    features: ['Configuracion en "L" o recta', "190 cm de largo - la mas grande", "Estructura de acero reforzado", "Ideal para setup con multiples monitores", "190 x 60 x 73 cm", "Envio GRATIS a todo Panama"],
    delivery: "Envio gratis a todo Panama por Red Servi (3-5 dias habiles)",
  },
];

export const ALL_PRODUCTS = [...SOFTWARE_PRODUCTS, ...DESK_PRODUCTS];

export function getProduct(id: string): Product | undefined {
  return ALL_PRODUCTS.find((p) => p.id === id);
}
